export default function () {
	return [{
		id: '5a581687252ca12c1445e5a9',
		picture: 'http://placehold.it/48x48',
		age: 22,
		first: 'Martin',
		last: 'Patrick',
		gender: 'male',
		phone: '(898) 519-2224',
		company: 'AFFLUEX',
		email: 'martinpatrick@affluex.com',
		address: '923 Buffalo Avenue, Springhill, Michigan, 1189',
		about: 'Est ut duis sunt ex veniam nisi ad officia eu et qui aliqua. Do sit nisi ea aliqua. Excepteur qui reprehenderit pariatur officia sunt laboris non est officia proident aliquip id.\r\n',
	},
	{
		id: '5a5816873bf467a85396e791',
		picture: 'http://placehold.it/48x48',
		age: 20,
		first: 'Delacruz',
		last: 'Waller',
		gender: 'male',
		phone: '(911) 541-2074',
		company: 'EMERGENT',
		email: 'delacruzwaller@emergent.com',
		address: '344 Will Place, Fowlerville, Ohio, 6261',
		about: 'Dolor aliquip do culpa et eu officia ex tempor Lorem dolor eu eiusmod. Minim voluptate eu do Lorem exercitation. Eiusmod eu mollit cupidatat id anim anim proident ullamco aliquip nisi proident ad culpa. Consequat consequat amet officia ea aute fugiat duis qui amet labore exercitation laboris. Ex eiusmod culpa commodo elit est amet ex et culpa ad. Ullamco adipisicing eiusmod occaecat ipsum in enim duis anim. Et dolor excepteur ut esse proident do consectetur.\r\n',
	},
	{
		id: '5a5816875717a397293df5ab',
		picture: 'http://placehold.it/48x48',
		age: 33,
		first: 'Noelle',
		last: 'Weiss',
		gender: 'female',
		phone: '(846) 515-3252',
		company: 'GLASSTEP',
		email: 'noelleweiss@glasstep.com',
		address: '592 Concord Street, Terlingua, Wisconsin, 9613',
		about: 'Reprehenderit proident dolore Lorem aliquip consequat amet eu ullamco deserunt amet proident elit. Ullamco consectetur sit ea nostrud. Ad commodo adipisicing voluptate ea ullamco enim consectetur aute officia excepteur nisi. Laboris sint laboris sit aliqua laboris veniam sunt aute enim. Eu tempor adipisicing cupidatat aute ut voluptate laborum nulla labore ad Lorem.\r\n',
	},
	{
		id: '5a58168739c861353d8c54b6',
		picture: 'http://placehold.it/48x48',
		age: 22,
		first: 'Walton',
		last: 'Wall',
		gender: 'male',
		phone: '(919) 544-3370',
		company: 'TALKOLA',
		email: 'waltonwall@talkola.com',
		address: '794 Devon Avenue, Lithium, Kansas, 5528',
		about: 'Id sint elit fugiat duis excepteur ea minim veniam voluptate. Nisi esse anim proident dolor in do excepteur anim anim sint est pariatur. Commodo nulla aliquip cillum sit sunt aute velit sit aliqua. Ut duis culpa esse ea pariatur Lorem eiusmod aliqua sit id. Ea exercitation consectetur irure culpa aliquip pariatur voluptate pariatur. Culpa nisi qui incididunt sunt proident.\r\n',
	},
	{
		id: '5a581687f5db230a3fd3241c',
		picture: 'http://placehold.it/48x48',
		age: 37,
		first: 'Ladonna',
		last: 'Fletcher',
		gender: 'female',
		phone: '(883) 401-3744',
		company: 'DECRATEX',
		email: 'ladonnafletcher@decratex.com',
		address: '439 Gatling Place, Blackgum, Idaho, 7648',
		about: 'Sint occaecat consectetur mollit fugiat quis laboris ea eu anim Lorem elit duis sit. Non quis proident magna ea sit. Lorem fugiat nisi consectetur quis consectetur voluptate qui magna adipisicing.\r\n',
	},
	{
		id: '5a58168772fca824040e9ee8',
		picture: 'http://placehold.it/48x48',
		age: 37,
		first: 'Callie',
		last: 'Knapp',
		gender: 'female',
		phone: '(829) 447-2529',
		company: 'BITTOR',
		email: 'callieknapp@bittor.com',
		address: '499 Monument Walk, Rote, California, 896',
		about: 'Aliqua non culpa laborum nulla irure nulla veniam laborum laborum esse. Consectetur reprehenderit non velit pariatur in et qui ullamco qui aliquip. Commodo minim occaecat irure sit ipsum veniam non commodo minim esse eiusmod velit. Eiusmod id ullamco dolore ullamco Lorem. In laboris excepteur ea nostrud elit.\r\n',
	},
	];
}
